version: '3.8'

services:
  gestion-usuarios-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    container_name: gestion-usuarios-backend
    env_file:
      - .env
